name: flutter_client
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_iconly: ^1.0.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.13
  gradient_borders: ^1.0.1
  iconsax: ^0.0.8
  image_cropper: ^8.0.2
  image_picker: ^1.1.2
  lottie: ^3.1.3
  provider: ^6.1.2
  simple_gradient_text: ^1.3.0
  string_validator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svgs/
    - assets/icons/
    - assets/lottie/
    - assets/images/
